set nocompatible

" use syntax highlighting and plugins
syntax on
filetype plugin on

" general settings
set showcmd
set noerrorbells
set number
set autochdir
set backspace=indent,eol,start
set fileformats=unix,dos,mac

" show whitespace
set listchars=tab:>-,trail:~,extends:>,precedes:<
set list

" make search nicer
set incsearch
set hlsearch
set ignorecase
set smartcase

" move backup and temp files
set backup
set backupdir=~/.vim/backup
set directory=~/.vim/tmp

" fix uppercase commands
command WQ wq
command Wq wq
command W w
command Q q

" fix cursor movement on wrapped lines
noremap j gj
noremap k gk

" hitting <CR> clears the search highlighting
nnoremap <CR> :nohlsearch<CR>/<BS><CR>

" move lines with ctrl+shift+j/k
nnoremap <C-S-k> ddkP
nnoremap <C-S-j> ddp
inoremap <C-S-j> <Esc>ddpi
inoremap <C-S-k> <Esc>ddkPi

" highlight lines that are longer than 77 characters
au BufWinEnter * let w:m1=matchadd('Search', '\%<81v.\%>77v', -1)
au BufWinEnter * let w:m2=matchadd('ErrorMsg', '\%>80v.\+', -1)

" remove trailing space from all lines when saving
au BufWritePre * silent! :%s/\s\+$//g
